services: 
  off-db: 
    container_name: off-db
    image: mongo:4
    restart: unless-stopped
    ports: 
      - 27018:27017
    env_file: .env
    volumes: 
      - ./openfoodfacts/entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./openfoodfacts/db:/openfoodfacts
    networks:
      - bigdata-network
  uptake: 
    container_name: uptake
    restart: unless-stopped
    build: 
      context: ./uptake
    volumes:
      - ./uptake/app:/app
      - ./uptake/datas:/data/dump
      - ./uptake/entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27019:27017
    networks:
      - bigdata-network
  spark:
    container_name: spark-py
    build:
      context: ./spark
      dockerfile: Dockerfile
    command: >
      /opt/spark/bin/spark-submit
      --packages org.mongodb.spark:mongo-spark-connector_2.12:3.0.1
      --conf spark.jars.ivy=/opt/spark/.ivy2
      --conf spark.local.dir=/tmp/spark-events
      /var/data/nutritional_index_classification.py
    volumes:
      - ./spark/datas:/var/data
      - spark_ivy_cache:/opt/spark/.ivy2
    env_file: .env
    environment:
      - SPARK_MASTER=local[*]
    depends_on:
      - off-db
    networks:
      - bigdata-network

volumes:
  spark_ivy_cache:

networks:
  bigdata-network: 
    driver: bridge