services: 
  mongodb: 
    container_name: openfoodfacts
    image: mongo:latest
    restart: unless-stopped
    ports: 
      - 27018:27017
    env_file: .env
    volumes: 
      - ./openfoodfacts/entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./openfoodfacts/db:/openfoodfacts