version: '3.9'
services: 
  mongodb: 
    container_name: openfoodfacts
    image: mongo:latest
    restart: unless-stopped
    ports: 
      - 27017:27017
    env_file: .env
    volumes: 
      - ./entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./db:/openfoodfacts
      - ./datas:/data/db